version: '3'
services:
  reolink-ftp-webhook:
    build: .
    ports:
      - ${FTP_PORT}:1234
    environment:
      FTP_USERNAME: ${FTP_USERNAME}
      FTP_PASSWORD: ${FTP_PASSWORD}
      WEBHOOK_URL: ${WEBHOOK_URL}
      WEBHOOK_METHOD: ${WEBHOOK_METHOD}
    logging:
      driver: 'local'
      options:
        max-size: '200k'
